kind: Service
apiVersion: v1
metadata:
  name: my-echo-service
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30002
      targetPort: 8080
  type: NodePort