apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echo-server-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: johnnyluo/echo-server:latest
        ports:
        - containerPort: 8080